;ЛАБ №3 ЗАДАНИЕ 6 МОДУЛЬ M1 (см. модуль M2)
DSEG	SEGMENT PUBLIC
	D1	DB 'D'
DSEG ENDS

	PUBLIC D1
CSEG	SEGMENT 
		ASSUME CS:CSEG, DS:DSEG
	EXTRN PP2:NEAR
	PP1	PROC
		CALL	PP2
		MOV		AH,4Ch
		INT	21h
	PP1	ENDP
CSEG	ENDS
	END PP1
