PUBLIC NEWSTR
PUBLIC OUTPUTSIGNBIN
PUBLIC OUTPUTUNSIGNHEX

EXTRN SIGNBINNUMBER: BYTE
EXTRN UNSIGNHEXNUMBER: BYTE
EXTRN SIGNFORHEX: BYTE
EXTRN DECTOUHEX: NEAR
EXTRN DECTOSBIN: NEAR


; Сегмент данных
DATAS SEGMENT PARA PUBLIC 'DATA'
	OUTPUTHEXMSG DB 'Unsigned hexadecimal number: $'
	OUTPUTBINMSG DB 'Signed binary number: $'
DATAS ENDS	

; Сегмент кода
CODES SEGMENT PARA PUBLIC 'CODE'	
    ASSUME CS:CODES, DS:DATAS
	
; Перевод на новую строку
NEWSTR PROC NEAR
	MOV AH, 2
	MOV DL, 13
	INT 21h
	MOV DL, 10
	INT 21h
	RET
NEWSTR ENDP

OUTPUTUNSIGNHEX PROC NEAR
	MOV DX, OFFSET OUTPUTHEXMSG
	MOV AH, 9
	INT 21h
	
	CALL DECTOUHEX
	
	MOV DX, OFFSET UNSIGNHEXNUMBER
	MOV AH, 9
	INT 21h
	
	CALL NEWSTR
	CALL NEWSTR
	CALL NEWSTR
	RET
OUTPUTUNSIGNHEX ENDP


OUTPUTSIGNBIN PROC NEAR
	MOV DX, OFFSET OUTPUTBINMSG
	MOV AH, 9
	INT 21h
	
	CALL DECTOSBIN
	
	XOR DX, DX
	MOV DL, BYTE PTR SIGNFORHEX
	MOV AH, 2
	INT 21h
	
	MOV DX, OFFSET SIGNBINNUMBER
	MOV AH, 9
	INT 21h
	
	CALL NEWSTR
	CALL NEWSTR
	CALL NEWSTR
	RET
OUTPUTSIGNBIN ENDP

CODES ENDS
END